// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Line01 struct {
	ID          int32
	UserID      string
	FileName    string
	FileContent sql.NullString
	CreatedAt   time.Time
	Theme       sql.NullString
}
